apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvl-test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: pvl-nvme-storage
