apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvl-test-pvc-restore
spec:
  dataSource:
    name: csi-pvl-test-snapshot 
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
