apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    environment: prod
spec:
  template:
    metadata:
      name: myapps
      labels:
        environment: prod
      
    spec:
      containers:
      - name: mypods
        image: nginx
        
  replicas: 2
  selector:
    matchLabels:
      environment: prod