apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp1
    type: front-end
  name: my-nginx-service
spec:
  ports:
  - port: 30019
    protocol: TCP
    targetPort: 30019
  selector:
    app: myapp1
    type: front-end
status:
  loadBalancer: {}
