apiVersion: v1
kind: Pod
metadata:
  name: my-nginx3
#  namespace: dev
  labels:
    app: myapp1
    type: front-end
#    environment: test
spec:
  containers:
    - name: my-nginx
      image: nginx
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "myapp1"
    effect: "NoSchedule"  