apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: sql
    name: mysql
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
