apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    environment: test
spec:
  template:
    metadata:
      name: myapps
      labels:
        environment: test
      
    spec:
      containers:
      - name: myni11
        image: nginx
        
  replicas: 2
  selector:
    matchLabels:
      
      environment: test