apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "1Gi"
    limits.cpu: "10"
    limits.memory: "5Gi"
    
      