apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-con
      image: busybox
      volumeDevices:
      - devicePath: /dev/pdnvme
        name: my-pvl-blkvol
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-pvl-blkvol
      persistentVolumeClaim:
        claimName: pvl-blockvol-pvc
