apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvl-blockvol-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: pvl-nvme-storage
  volumeMode: Block
