apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-src-pvc
spec:
  storageClassName: pvl-nvme-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: csi-pvl-src-pvc
    apiGroup: ""
