apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvl-src-pvc
spec:
  storageClassName: pvl-nvme-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
